### PR TITLE
Fix/grappelli templates

### PR DESCRIPTION
**Pull request by bensialih**
- fix for grappelli import
- refactored imports of js files to be centralized
- added page_js block to allow for page specific js

this is concerning the issue raised [here](https://github.com/kiwitcms/Kiwi/issues/2467#issuecomment-897751275)

### CODE REVIEW

**Comment by atodorov** [comment]
Thanks for the pull request. 

The changes are a bit invasive so let's start by narrowing down the problem. Is the fact that browser console reports a problem a real issue? Till now we haven't seen functionality break due to a problem with grappelli so it sounds to me more of a cosmetic type of thing. Can you explain what the real problem is ?

**Comment by bensialih** [comment]
hi @atodorov 

Thanks for looking at the code.

I think the template includes are really just to organize the js and css imports into one place.
Maybe this is not necessary and may be better to have things on individual pages.

There is the second and real issue of grappelli.
Grappelli is not the issue on all the other pages except for the "new item" pages as cited here
https://github.com/kiwitcms/Kiwi/issues/2467

Grappelli should be included as a global variable wherever its used otherwise you will get the error cited.

page_js block is also to organize files that are used specific to the calling django page.

**Comment by atodorov** [comment]
> Grappelli is not the issue on all the other pages except for the "new item" pages as cited here
> #2467

grappelli is not the root cause of the bug in #2467 as commented in https://github.com/kiwitcms/Kiwi/issues/2467#issuecomment-893434441. 

> Grappelli should be included as a global variable wherever its used otherwise you will get the error cited.

Let's try this again. If we don't merge the changes in this PR what is the actual problem which is caused by the missing definition of a global grappelli variable ?  Which functionality is not working ?

**Comment by bensialih** [comment]
Ah ok.
Thank you.

**Pull request closed without merging**
