### PR TITLE
[Snyk] Fix for 2 vulnerable dependencies

### PR DESCRIPTION
**Pull request by atodorov**
#### Description
This PR fixes one or more vulnerable packages in the `npm` dependencies of this project.
See the [Snyk test report](https://snyk.io/test/github/fc609e73-6e5b-42da-a5a4-db398f1a1fe9/master..snyk-fix-31eu2n) for more details.

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - package.json

##### With an upgrade:
- [npm:moment:20161019](https://snyk.io/vuln/npm:moment:20161019)
- [npm:moment:20170905](https://snyk.io/vuln/npm:moment:20170905)

You can read more about Snyk's upgrade and patch logic in [Snyk's documentation](https://snyk.io/docs/using-snyk/).

Check the changes in this PR to ensure they won't cause issues with your project.

Stay secure,
The Snyk team

[//]: # (snyk:metadata:{"type":"auto","packageManager":"npm","vulns":["npm:moment:20161019","npm:moment:20170905"],"patch":[],"upgrade":["npm:moment:20161019","npm:moment:20170905"],"isBreakingChange":false,"env":"prod"})

### CODE REVIEW

**Comment by atodorov** [comment]
NOTE: before merging we have to figure out if the new patternfly version leads to any issues with the UI. 

Automated tests will not catch this as of now so it is a manual process.

**Comment by atodorov** [comment]
@asankov this update breaks the navigation menu. My guess is that the HTML layout in Patternfly has changed. Can you look into it and push more commits to the current branch before we can merge this PR.

**Comment by asankov** [comment]
Okay. Will look at it over the weekend.

**Comment by asankov** [comment]
The problem turned out to be that before the update (`patternfly: 3.30`) all the patternfly files were under `node_modules/`. However, after the update (`patternfly: 3.36`) they were moved to `node_modules/paternfly/node_modules`. Therefore, the references we had to them were no longer existing, and the files could not have been found. This is also visible from the server logs. 

This commit fixes the change: https://github.com/asankov/Kiwi/commit/607ca6b9d8a3ab2177e9459c90bc9a9a8b2a6845

But I have no right to push into this branch. Maybe you could just cherry-pick it.

**Pull request merged**
