### PR TITLE
Resolves #1531 Add "insert table" button to toolbar

### LINKED ISSUE #1531: Add buttons for creating tables in text editor - SimpleMDE
The text editor that we use is called SimpleMDE.

Kiwi TCMS needs a way to insert tables in the document for users who are not familiar with the markdown syntax. 

SimpleMDE has the ability to define custom buttons so something like the following will do the trick:

**Definition of Done**:
1. A button to insert a table, say 3x3
2. A button to insert a new row, below the currently selected one
3. A button to delete the current row
4. A button to insert a column, to the right of the currently selected one
5. A button to delete the current column

For more info see the **insertTexts** and **Custom Button** examples at:
https://github.com/sparksuite/simplemde-markdown-editor

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

### PR DESCRIPTION
**Pull request by brymut**
Resolves #1531 Change adds "table" toolbar option in SimpleMDE config

### CODE REVIEW

**Comment by atodorov** [comment]
The insert table button looks good, needs the rest of the items from the original issue.

**Comment by atodorov** [comment]
> The insert table button looks good, needs the rest of the items from the original issue.

@brymut ping. Are you going to resolve work on this one ?

**Comment by brymut** [comment]
> @brymut ping. Are you going to resolve work on this one ?

I don't think I'll be able to, seems like it would need quite a bit of extension to SimpleMDE.

**Comment by atodorov** [comment]
> I don't think I'll be able to, seems like it would need quite a bit of extension to SimpleMDE.

@brymut fair enough. I have cherry-picked your commit and updated the commit log message to match. The new button is still a good addition and the rest needs to be handled separately.

**Pull request closed without merging**
