### PR TITLE
add type checking

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
so it looks like it will be possible to add type checking to most of this code base relatively easily, with one major exception. Django is pretty antagonistic to type checking. There's a [mypy plugin](https://github.com/typeddjango/django-stubs) but getting it to work for all cases will require a little black magic and more django experience than i possess.

I'm still digging around, but it might make sense to exlude this for now in favour of getting the basic infrastructure working

**Comment by danieleades** [comment]
don't think the CI failures are related to this PR

**Comment by atodorov** [comment]
Won't persue this direction at all, no need to spend any time in adding type checking.

**Comment by danieleades** [comment]
> Won't persue this direction at all, no need to spend any time in adding type checking. 

Can I ask why type checking is not of interest?

**Pull request closed without merging**
