### PR TITLE
Provide OptIn parameter to not enforce HTTPS fixes #1036

### LINKED ISSUE #1036: Provide OptIn parameter to not enforce HTTPS
### Description of problem
The current docker image does enforce HTTPS by redirecting HTTP requests to the Apache HTTPS port. This makes configuration behind a reverse proxy unecessarily complicated.

I will provide a pull request, where an additional parameter may be passed to not enforce this HTTP -> HTTPS redirection.

An example invocation will then look like

```
docker run -e NoEnforceHTTPS=true
```

This request does not collide with #997 as the feature is an entire **OptIn** which has to be carried out by a responsible system administrator, but greatly eases its work.

If this gets accepted, I might provide an additional parameter (again **OptIn**) to deactive ssl processing at all. This will lower the dockers instances system resource requirements.

### Version or commit hash (if applicable)
current

### Steps to Reproduce

1. start a current docker instance

### Actual results
HTTP requests are redirected to HTTPS

### Expected results
Leave direct HTTP access open, such that I can care for HTTPS termination at the upstream reverse proxy.

### PR DESCRIPTION
**Pull request by col-panic**
See #1036  for issue

### CODE REVIEW

**Comment by atodorov** [comment]
Also add `Fixes #1036` to the end of your commit log message.

**Comment by col-panic** [comment]
Here you are. Please consider porting this patch to the newest stable branch, such that I can use it in a productive environment.

**Comment by atodorov** [comment]
> Please consider porting this patch to the newest stable branch, such that I can use it in a productive environment.

we don't release via multiple branches so that means master where this PR lands. You can always rebuild the docker image from the master branch and use a DIY version if you need this urgently. Given we had a new release last Friday there probably won't be another one for the next few weeks.

**Comment by col-panic** [comment]
thx!

**Pull request merged**
