### PR TITLE
Fix for Azure integration tests

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@cmbahadir can you make sense of the failure and the latest log data ? 

This test started failing after Dec 14th (see commits on master branch when it was executed last successfully).

The known issue URL is https://dev.azure.com/kiwitcms/boards-integration/_workitems/edit/1

From what I can see authentication works just fine b/c new comments are being posted on Azure however reading all of them is likely a problem. I see the GET call executed hundreds of times and eventually the remote host terminates the connection. 

On top of that the cleanup in the test doesn't appear to be doing it's job well b/c Azure says there are 232 comments on this issue.

**Comment by cmbahadir** [comment]
Hi @atodorov, i think your PR is intended to be a temporary solution, isn't it?

I have just saw your mention.

**Comment by cmbahadir** [comment]
Well i have checked the issue and it seems like azure boards aborts connection if the response gets too long. 

IMO, deleting comment after test would be the best option.

Another solution would be using "$top" parameter to limit the returning comments, but in that case checking the comment count to see if the latest test comment is added will have to change. So i can pull this and implement the "delete_comment" for azure boards, if that you are fine with deleting the previous comments.

**Comment by atodorov** [comment]
> Well i have checked the issue and it seems like azure boards aborts connection if the response gets too long.
> 
> IMO, deleting comment after test would be the best option.
> 

Yup, delete solves the issue but the reason for aborted connection is not what you think. See commit message in the second commit.

> Another solution would be using "$top" parameter to limit the returning comments, 

That won't help b/c it doesn't matter of you return 200 or 1000. At some point you'll fetch all of the first N comments and need to do pagination and end up in the same scenario like now.

> but in that case checking the comment count to see if the latest test comment is added will have to change. 

This still needs to change because it isn't very robust. In my own testing it looks like a comment gets reflected around 1 second after we initiate the POST. time.sleep() is not a good option, checking the count either, checking the id of the last one either (b/c when you reach maximum if deletion has failed unnoticed these IDs won't change).  

It may be possible to loop and search for the last comment added in the last X seconds (say 5-10) but this is prone to failures in case the network goes bad (we can live with it) but is also prone to race conditions with parallel pull requests. But I guess the current implementation is also subject to race conditions and we haven't had an issue with that so far. 

Feel free to send a PR if you come up with something better than what we've got now.

**Comment by cmbahadir** [comment]
I didn't know that the "count" is limited to 200, so using "totalCount" could also be an option.

https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/comments/get%20comments?view=azure-devops-rest-6.1#commentlist

Handling ascynchronization with race conditions might still be problem. I will open a PR, if i can find a better way to handle it.

**Pull request merged**
