### PR TITLE
WIP: ci(sanity): migrate 'test-for-missing-migrations'

### LINKED ISSUE #1553: Travis CI -> GitHub workflow: test-for-missing-migrations
Kiwi TCMS needs help migrating certain test jobs from Travis CI into GitHub workflows. In particular the `test-for-missing-migrations` job.

**Definition of Done**:
- "test-for-missing-migrations" job has been removed from Travis CI
- "sanity / test-for-missing-migrations" job is enabled for GitHub workflows. See `.github/workflows/lint.yml` and create a `sanity.yml`
- The new job reports its result on the pull request

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

### PR DESCRIPTION
**Pull request by PauloGoncalvesBH**
Migration from Travis CI to GitHub Workflow

fix #1553

### CODE REVIEW

**Comment by atodorov** [comment]
> include "... .Fix #1553" at the end of the message.

I think you mean we prefer this to be at the end of the 1st line of the commit log message.

**Comment by PauloGoncalvesBH** [comment]
@atodorov @RMadjev 
According to 'conventional commits', the reference to the issue must be in the footer.

[Conventional Commit - Footer section](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers)

image

**Comment by atodorov** [comment]
> @atodorov @RMadjev
> According to 'conventional commits', the reference to the issue must be in the footer, and that's exactly what I did.

Right, what you did isn't wrong, it is just less practical. GitHub truncates everything except the first line so if you add the Fixes reference on the first line it just makes things easier to see in the GitHub webUI.

**Comment by atodorov** [comment]
@PauloGoncalvesBH ping, any news here ?

**Comment by atodorov** [comment]
@brymut FYI ^^^, related to #1752

**Comment by atodorov** [comment]
closed in favor of https://github.com/kiwitcms/Kiwi/pull/1753

**Pull request closed without merging**
